<div class='head_item_left'>
			Verleih
</div>
	<div class="menu_list" id="jq_slide_by_click_1"> 
	<p class="menu_head">Allgemein</p>
	<div class="menu_body">
		<a href="../../admin_srb_verleih/vl_find.php">Verleih finden</a>
		<a href="../../admin_srb_adress/adress_find.php">Verleih buchen</a>
		<a href="../../admin_srb_inventar/iv_find.php">Inventar finden</a>
	</div>		

	<p class="menu_head">Listen</p>
	<div class="menu_body">
		<a href="../../admin_srb_verleih/vl_find_list.php?action=list&amp;find_option=vl_new_items">Neuester Verleih</a>
		<a href="../../admin_srb_verleih/vl_find_list.php?action=list&amp;find_option=vl_this_month">Ausleihe diesen Monat</a>
		<a href="../../admin_srb_verleih/vl_find_list.php?action=list&amp;find_option=vl_open_items">Offener Verleih</a>
		<a href="../../admin_srb_inventar/iv_kat_list.php?action=list&amp;find_option=gesamt">Inventar Kategorie listen</a>
		<a href="../../admin_srb_inventar/iv_find_list.php?action=list&amp;find_option=verliehen_gesamt">Inventar verliehene Objekte listen</a>
	</div>	
	
	<p class="menu_head">Statistik</p>
	<div class="menu_body">
		<a href="../../admin_srb_verleih/vl_statistik.php?action=display" class="c_box">Statistik anzeigen</a>
	</div>

</div>


