<div class="content">
<div>
	<a href="../../admin_srb_verleih/vl_find.php" title= 'Verleih finden'><img src='../parts/pict/Snapture.png' width='32px' height='32px' title='Verleih finden' alt='Verleih finden'></a>			
	<a href="../../admin_srb_adress/adress_find.php" id='first_element_of_toolbar' title= 'Neuen Verleih buchen'><img src='../parts/pict/1281368175_limited-edition.png' width='32px' height='32px' title='Neuer Verleih' alt='Neuer Verleih'></a>
	<a href="../../admin_srb_verleih/vl_find_list.php?action=list&amp;find_option=vl_new_items" title= 'Neuen Verleih listen'><img src='../parts/pict/Maps.png' width='32px' height='32px' title='Neuen Verleih listen' alt='Neuen Verleih listen'></a>
	<a href="../../admin_srb_verleih/vl_find_list.php?action=list&amp;find_option=vl_open_items" title= 'Offenen Verleih listen'><img src='../parts/pict/1281368175_limited-edition_half.png' width='32px' height='32px' title='Offenen Verleih listen' alt='Offenen Verleih listen'></a>
</div>
</div>