<div class='head_item_left'>
	Sendung
</div>
<div class="menu_list" id="jq_slide_by_click_1"> 
	<p class="menu_head">Allgemein</p>
	<div class="menu_body">
		<a href="../../admin_srb_sendung_hf/sg_hf_find.php">Sendung finden</a>
		<a href="../../admin_srb_adress/adress_find.php">Sendung buchen</a>
		<a href="../../admin_srb_sendung_hf/sg_hf_find_list.php?action=list&amp;find_option=prepared_all">Sendungen vorbereitet</a>
		<a href="../../admin_srb_play_out/play_out_log_find_list.php?action=list_today_play_out&amp;call_from_sendung=yes">Gespielte Titel heute/ Datum</a>
	</div>

	<p class="menu_head">Wochenlisten</p>
	<div class="menu_body">
		<a href="../../admin_srb_sendung_hf/sg_hf_list_week.php?action=list&amp;find_option=broadcast_week_all">Alle Sendungen dieser Woche</a>	
		<a href="../../admin_srb_sendung_hf/sg_hf_list_week.php?action=list&amp;find_option=broadcast_week_next_all">Alle Sendungen nächste Woche</a>		
		<a href="../../admin_srb_sendung_hf/sg_hf_list_week.php?action=list&amp;find_option=broadcast_week_previous_all">Alle Sendungen verg. Woche</a>
		<a href="../../admin_srb_sendung_hf/sg_hf_list_week.php?action=list&amp;find_option=broadcast_week_date_all">Alle Sendungen nach Datum</a>
		<a href="../../admin_srb_sendung_hf/sg_hf_list_week.php?action=list&amp;find_option=broadcast_normal_week_date_all">Normal-Sendungen nach Datum</a>
		<a href="../../admin_srb_sendung_hf/sg_hf_list_week.php?action=list&amp;find_option=infotime_week_date_all">Info-Time-Send. nach Datum</a>
		<a href="../../admin_srb_sendung_hf/sg_hf_list_week.php?action=list&amp;find_option=magazine_week_date_all">Magazin-Send. nach Datum</a>
	</div>

	<p class="menu_head">Kalender</p>
	<div class="menu_body">
		<a href="https://srb-radio.de/kalender">Sendeplanung</a>
		<a href="../../admin_srb_sendung_hf/sg_hf_cal_week.php?action=list&amp;find_option=broadcast_week_all" class="c_box_1">Alle Sendungen diese Woche</a>
		<a href="../../admin_srb_sendung_hf/sg_hf_cal_week.php?action=list&amp;find_option=broadcast_week_next_all" class="c_box_1">Alle Sendungen nächster Woche</a>
		<a href="../../admin_srb_sendung_hf/sg_hf_cal_week.php?action=list&amp;find_option=broadcast_week_previous_all" class="c_box_1">Alle Sendungen verg. Woche</a>
	</div>

	<p class="menu_head">Kalender drucken</p>
	<div class="menu_body">
		<a href="../../admin_srb_sendung_hf/index_sg_hf_cal_print.shtml">Übersicht/ Kalender nach Datum</a>

		<a href="../../admin_srb_sendung_hf/sg_hf_cal_week_print.php?action=list_dayback_7&amp;find_option=print_week_infotime">verg. Woche Info-Time </a>	
		<a href="../../admin_srb_sendung_hf/sg_hf_cal_week_print.php?action=list_dayback_7&amp;find_option=print_week_magazine">verg. Woche Magazin</a>		
		<a href="../../admin_srb_sendung_hf/sg_hf_cal_week_print.php?action=list_dayback_7&amp;find_option=print_week_broadcast">verg. Woche Sendungen</a>
			
		<a href="../../admin_srb_sendung_hf/sg_hf_cal_week_print.php?action=list_dayback_14&amp;find_option=print_week_infotime">vorige Woche Info-Time </a>	
		<a href="../../admin_srb_sendung_hf/sg_hf_cal_week_print.php?action=list_dayback_14&amp;find_option=print_week_magazine">vorige Woche Magazin</a>		
		<a href="../../admin_srb_sendung_hf/sg_hf_cal_week_print.php?action=list_dayback_14&amp;find_option=print_week_broadcast">vorige Woche Sendungen</a>

		<a href="../../admin_srb_sendung_hf/sg_hf_cal_week_print.php?action=list_forwards_7&amp;find_option=print_week_infotime">kommende Woche Info-Time</a>	
		<a href="../../admin_srb_sendung_hf/sg_hf_cal_week_print.php?action=list_forwards_7&amp;find_option=print_week_magazine">kommende Woche Magazin</a>		
		<a href="../../admin_srb_sendung_hf/sg_hf_cal_week_print.php?action=list_forwards_7&amp;find_option=print_week_broadcast">kommende Woche Sendungen</a>
		
		<a href="../../admin_srb_sendung_hf/sg_hf_cal_week_print.php?action=list_forwards_14&amp;find_option=print_week_infotime">In 14 Tagen Info-Time</a>	
		<a href="../../admin_srb_sendung_hf/sg_hf_cal_week_print.php?action=list_forwards_14&amp;find_option=print_week_magazine">In 14 Tagen Magazin</a>		
		<a href="../../admin_srb_sendung_hf/sg_hf_cal_week_print.php?action=list_forwards_14&amp;find_option=print_week_broadcast">In 14 Tagen Sendungen </a>

		<a href="../../admin_srb_sendung_hf/sg_hf_cal_week_print.php?action=list_forwards_21&amp;find_option=print_week_infotime">In drei Wochen Info-Time </a>	
		<a href="../../admin_srb_sendung_hf/sg_hf_cal_week_print.php?action=list_forwards_21&amp;find_option=print_week_magazine">In drei Wochen Magazin</a>		
		<a href="../../admin_srb_sendung_hf/sg_hf_cal_week_print.php?action=list_forwards_21&amp;find_option=print_week_broadcast">In drei Wochen Sendungen</a>

	</div>

	<p class="menu_head">Info-Time - Liste</p>
	<div class="menu_body">
		<a href="../../admin_srb_sendung_hf/sg_hf_find_list.php?action=list&amp;find_option=info_time_today">Info-Time heute</a>
		<a href="../../admin_srb_sendung_hf/sg_hf_find_list.php?action=list&amp;find_option=info_time_yesterday">Info-Time gestern</a>
		<a href="../../admin_srb_sendung_hf/sg_hf_find_list.php?action=list&amp;find_option=info_time_tomorrow">Info-Time morgen</a>
		<a href="../../admin_srb_sendung_hf/sg_hf_find_list.php?action=list&amp;find_option=info_time_after_tomorrow">Info-Time übermorgen</a>
		<a href="../../admin_srb_sendung_hf/sg_hf_find_list.php?action=list&amp;find_option=info_time_after_after_tomorrow">Info-Time über-übermorgen</a>
		<a href="../../admin_srb_sendung_hf/sg_hf_find_list.php?action=list&amp;find_option=info_time_four_days">Info-Time 4 Tage vor</a>
	</div>

	<p class="menu_head">Info-Time - Plan</p>
	<div class="menu_body">
		<a href="../../admin_srb_sendung_hf/sg_hf_plan.php?action=list&amp;find_option=info_time_today_a" class="c_box">Info-Time A heute</a>
		<a href="../../admin_srb_sendung_hf/sg_hf_plan.php?action=list&amp;find_option=info_time_yesterday_a" class="c_box">Info-Time A gestern</a>
		<a href="../../admin_srb_sendung_hf/sg_hf_plan.php?action=list&amp;find_option=info_time_tomorrow_a" class="c_box">Info-Time A morgen</a>
		<a href="../../admin_srb_sendung_hf/sg_hf_plan.php?action=list&amp;find_option=info_time_after_tomorrow_a" class="c_box">Info-Time A übermorgen</a>		
		<a href="../../admin_srb_sendung_hf/sg_hf_plan.php?action=list&amp;find_option=info_time_after_after_tomorrow_a" class="c_box">Info-Time A über-übermorgen</a>
		<a href="../../admin_srb_sendung_hf/sg_hf_plan.php?action=list&amp;find_option=info_time_four_days_a" class="c_box">Info-Time A 4 Tage vor</a>				
		<a href="../../admin_srb_sendung_hf/sg_hf_plan.php?action=list&amp;find_option=info_time_today_b" class="c_box">Info-Time B heute</a>
		<a href="../../admin_srb_sendung_hf/sg_hf_plan.php?action=list&amp;find_option=info_time_yesterday_b" class="c_box">Info-Time B gestern</a>
		<a href="../../admin_srb_sendung_hf/sg_hf_plan.php?action=list&amp;find_option=info_time_tomorrow_b" class="c_box">Info-Time B morgen</a>
		<a href="../../admin_srb_sendung_hf/sg_hf_plan.php?action=list&amp;find_option=info_time_after_tomorrow_b" class="c_box">Info-Time B übermorgen</a>		
		<a href="../../admin_srb_sendung_hf/sg_hf_plan.php?action=list&amp;find_option=info_time_after_after_tomorrow_b" class="c_box">Info-Time B über-übermorgen</a>
		<a href="../../admin_srb_sendung_hf/sg_hf_plan.php?action=list&amp;find_option=info_time_four_days_b" class="c_box">Info-Time B 4 Tage vor</a>
	</div>
	
	<p class="menu_head">Magazin - Liste</p>
	<div class="menu_body">

		<a href="../../admin_srb_sendung_hf/sg_hf_find_list.php?action=list&amp;find_option=magazine_today">Magazin heute</a>
		<a href="../../admin_srb_sendung_hf/sg_hf_find_list.php?action=list&amp;find_option=magazine_yesterday">Magazin gestern</a>		
		<a href="../../admin_srb_sendung_hf/sg_hf_find_list.php?action=list&amp;find_option=magazine_tomorrow">Magazin morgen</a>
		<a href="../../admin_srb_sendung_hf/sg_hf_find_list.php?action=list&amp;find_option=magazine_after_tomorrow">Magazin übermorgen</a>
		<a href="../../admin_srb_sendung_hf/sg_hf_find_list.php?action=list&amp;find_option=magazine_after_after_tomorrow">Magazin über-übermorgen</a>
		<a href="../../admin_srb_sendung_hf/sg_hf_find_list.php?action=list&amp;find_option=magazine_four_days">Magazin 4 Tage vor</a>
	</div>

	<p class="menu_head">Magazin - Plan</p>
	<div class="menu_body">
		<a href="../../admin_srb_sendung_hf/sg_hf_plan.php?action=list&amp;find_option=magazine_today" class="c_box">Magazin heute</a>
		<a href="../../admin_srb_sendung_hf/sg_hf_plan.php?action=list&amp;find_option=magazine_yesterday" class="c_box">Magazin gestern</a>
		<a href="../../admin_srb_sendung_hf/sg_hf_plan.php?action=list&amp;find_option=magazine_tomorrow" class="c_box">Magazin morgen</a>
		<a href="../../admin_srb_sendung_hf/sg_hf_plan.php?action=list&amp;find_option=magazine_after_tomorrow" class="c_box">Magazin übermorgen</a>		
		<a href="../../admin_srb_sendung_hf/sg_hf_plan.php?action=list&amp;find_option=magazine_after_after_tomorrow" class="c_box">Magazin über-übermorgen</a>
		<a href="../../admin_srb_sendung_hf/sg_hf_plan.php?action=list&amp;find_option=magazine_four_days" class="c_box">Magazin 4 Tage vor</a>
	</div>
	
	<p class="menu_head">Sendungen</p>
	<div class="menu_body">
		<a href="../../admin_srb_sendung_hf/sg_hf_find_list.php?action=list&amp;find_option=broadcast_today">Sendung heute</a>
		<a href="../../admin_srb_sendung_hf/sg_hf_find_list.php?action=list&amp;find_option=broadcast_yesterday">Sendung gestern</a>
		<a href="../../admin_srb_sendung_hf/sg_hf_find_list.php?action=list&amp;find_option=broadcast_tomorrow">Sendung morgen</a>
		<a href="../../admin_srb_sendung_hf/sg_hf_find_list.php?action=list&amp;find_option=broadcast_after_tomorrow">Sendung übermorgen</a>
		<a href="../../admin_srb_sendung_hf/sg_hf_find_list.php?action=list&amp;find_option=broadcast_after_after_tomorrow">Sendung über-übermorgen</a>
		<a href="../../admin_srb_sendung_hf/sg_hf_find_list.php?action=list&amp;find_option=broadcast_four_days">Sendung 4 Tage vor</a>
	</div>
	
	<p class="menu_head">Einstellungen</p>
	<div class="menu_body">
		<a href="../../admin_srb_user/user_special_detail.php?action=display&amp;special_id=1049941">Texte Sendeanmeldung</a>
		<a href="../../admin_srb_sendung_hf/sg_hf_robot_find_list.php?action=list&find_option=sg_titel">Automatisierte Sendungen</a>
		<a href="../../admin_srb_sendung_hf/sg_hf_robot_edit.php?action=new&sg_robot_id=0" class="c_box">Automatisierte Sendung neu</a>
	</div>

	<p class="menu_head">Statistik</p>
	<div class="menu_body">
		<a href="../../admin_srb_sendung_hf/sg_hf_statistik.php?action=display" class="c_box">Statistik anzeigen</a>
	</div>
	
</div>


