<div class="content">
<div>
	<a href="../../admin_srb_sendung_hf/sg_hf_find.php" id='first_element_of_toolbar' title='Sendung finden'><img src='../parts/pict/1279186711_search-database.png' width='32px' height='32px' title='Sendung finden' alt='Sendung finden'></a> 		
	<a href="../../admin_srb_adress/adress_find.php" title= 'Neue Sendung buchen'><img src='../parts/pict/1279186076_sign-up.png' width='32px' height='32px' title='Neue Sendung' alt='Neue Sendung'></a>
	<a href="https://srb-radio.de/kalender/cal_broadcast.html" target="_blank" title='Sendeplanung'><img src='../parts/pict/1279122360_youtube_alt.png' width='32px' height='32px' title='Sendeplanung' alt='Sendeplanung'></a>		
	<a href="../../admin_srb_sendung_hf/sg_hf_cal_week.php?action=list&amp;find_option=broadcast_week_all" class="c_box_1" title='Kalender alle Sendungen diese Woche'><img src='../parts/pict/1279188955_order-history.png' width='32px' height='32px' title='Kalender Sendungen diese Woche' alt='Kalender Sendungen diese Woche'></a>			
	<a href="../../admin_srb_sendung_hf/sg_hf_list_week.php?action=list&amp;find_option=infotime_week_date_all" title='Liste aller Infotimesendungen diese Woche'><img src='../parts/pict/file_temporary.png' width='32px' height='32px' title='Infotimesendungen diese Woche' alt='Infotimesendungen diese Woche'></a>	
	<a href="../../admin_srb_sendung_hf/sg_hf_list_week.php?action=list&amp;find_option=magazine_week_date_all" title='Liste aller Magazinsendungen diese Woche'><img src='../parts/pict/application-vnd.oasis.opendocument.text.png' width='32px' height='32px' title='Magazinsendungen diese Woche' alt='Magazinsendungen diese Woche'></a>
	<a href="../../admin_srb_sendung_hf/sg_hf_list_week.php?action=list&amp;find_option=broadcast_normal_week_date_all" title='Liste aller Normal-Sendungen diese Woche'><img src='../parts/pict/1279186092_reports.png' width='32px' height='32px' title='Normal-Sendungen diese Woche' alt='Normal-Sendungen diese Woche'></a>
</div>
</div>