<div class='head_item_left'>
	Adresse
</div>
<div class="menu_list" id="jq_slide_by_click_1"> 
	<p class="menu_head">Allgemein</p>
	<div class="menu_body">
		<a href="../../admin_srb_adress/adress_find.php">Adresse finden</a>
		<a href="../../admin_srb_adress/adress_edit.php?action=new&amp;ad_id=0" class='c_box'>Adresse eintragen</a>
	</div>		

	<p class="menu_head">Listen</p>
	<div class="menu_body">
		<a href="../../admin_srb_adress/adress_find_list.php?action=list&amp;find_option=active_user">Aktive Macher dieses Quartal</a>
		<a href="../../admin_srb_adress/adress_find_list.php?action=list&amp;find_option=user_hf">Macher Hörfunk</a>
		<a href="../../admin_srb_adress/adress_find_list.php?action=list&amp;find_option=user_tv">Macher Fernsehen</a>
		<a href="../../admin_srb_adress/adress_find_list.php?action=list&amp;find_option=user_tv_and_hf">Macher gleichz. TV und HF</a>
		<a href="../../admin_srb_adress/adress_find_list.php?action=list&amp;find_option=birthday_this_month">Geburtstage diesen Monat</a>
		<a href="../../admin_srb_adress/adress_find_list.php?action=list&amp;find_option=birthday_next_month">Geburtstage nächsten Monat</a>
	</div>	
	
	<p class="menu_head">Statistik</p>
	<div class="menu_body">
		<a href="../../admin_srb_adress/adress_statistik.php?action=display" class='c_box'>Statistik anzeigen</a>
	</div>

	<p class="menu_head">Einstellungen</p>
	<div class="menu_body">
		<a href="../../admin_srb_user/user_special_detail.php?action=display&amp;special_id=1048516">Texte Nutzerformular</a>
		<a href="../../admin_srb_user/user_special_detail.php?action=display&amp;special_id=1060379">Texte Einwilligungserklärung</a>
		<a href="../../admin_srb_user/user_look_ups_list.php?action=list&amp;find_option=ad_titel">Bezeichnungen Titel</a>
	</div>		
</div>


