<div class="content">
<div>
	<a href="../../admin_srb_adress/adress_find.php"  title='Adresse finden'><img id='first_element_of_toolbar' src='../parts/pict/forum.png' width='32px' height='32px' title='Adresse finden' alt='Adresse finden'></a>
	<a href="../../admin_srb_adress/adress_edit.php?action=new&amp;ad_id=0" class='c_box' title='Neue Adresse eintragen'><img src='../parts/pict/workspace2.png' width='32px' height='32px' title='Neue Adresse eintragen' alt='Neue Adresse eintragen'></a>
</div>
</div>

 