<div class="head_item_left">
	<b>Inventar</b>	
</div>

<div class="menu_list" id="jq_slide_by_click_1"> 
	<p class="menu_head"><a href="index.php">Inventar-Home</a>	</p>
	<p class="menu_head">Allgemein</p>
	<div class="menu_body">
		<a href="iv_find.php">Inventar finden</a>
		<a href="../../admin_srb_inventar/iv_edit.php?action=new&amp;iv_id=1" class='c_box_2'>Inventar eintragen</a>
	</div>				
	<p class="menu_head">Listen</p>
	<div class="menu_body">
		<a href="../../admin_srb_inventar/iv_find_list.php?action=list&amp;find_option=gesamt">Inventar alphabetisch listen</a>
		<a href="../../admin_srb_inventar/iv_find_list.php?action=list&amp;find_option=gesamt_datum">Inventar nach Anschaffungsdatum</a>
		<a href="../../admin_srb_inventar/iv_kat_list.php?action=list&amp;find_option=gesamt">Inventar Kategorie listen</a>
		<a href="../../admin_srb_inventar/iv_find_list.php?action=list&amp;find_option=verliehen_gesamt">Verliehene Objekte listen</a>
		<a href="../../admin_srb_inventar/iv_find_list.php?action=list&amp;find_option=defekt_gesamt">Defekte Objekte listen</a>
		<a href="../../admin_srb_inventar/iv_find_list.php?action=list&amp;find_option=ausgemustert_gesamt">Ausgemusterte Objekte listen</a>
	</div>				
		
	<p class="menu_head">Listen - PDF</p>
	<div class="menu_body">
		<a href="../../admin_srb_inventar/iv_pdf_list.php?action=list&amp;find_option=gesamt">Liste gesamt</a>
		<a href="../../admin_srb_inventar/iv_pdf_list.php?action=list&amp;find_option=gesamt_ohne_buecherei">Liste gesamt ohne Bücherei</a>
		<a href="../../admin_srb_inventar/iv_pdf_list.php?action=list&amp;find_option=gesamt_ohne_buecherei_mit_text">Liste gesamt ohne Bücherei mit Text</a>
		<a href="../../admin_srb_inventar/iv_pdf_pref.php">Listen definieren</a>
	</div>				
	<p class="menu_head">Einstellungen</p>
	<div class="menu_body">
		<a href="../../admin_srb_user/user_look_ups_list.php?action=list&amp;find_option=iv_kategorie">Inventar Kategorien</a>
		<a href="../../admin_srb_user/user_look_ups_list.php?action=list&amp;find_option=iv_eigentuemer">Inventar Eigentuemer</a>
	</div>
</div>
