<div class="content">
<div>
	<a href="../../admin_srb_inventar/iv_find.php" title='Inventar finden'><img src='../parts/pict/1279186711_search-database.png' width='32px' height='32px' title='Inventar finden' alt='Inventar finden'></a> 		
	<a href="../../admin_srb_inventar/iv_edit.php?action=new&amp;iv_id=1" class='c_box'" title= 'Neues Inventarobjekt aufnehmen'><img src='../parts/pict/1279186076_sign-up.png' width='32px' height='32px' title='Neues Inventarobjekt' alt='Neues Inventarobjekt'></a>
</div>
</div>