<div class="menu_top">
	<ul class="menu_top_list">
		<li><a href="index.shtml">Home</a></li>
		<li><a href="admin_srb_adress/index.php" id="first_element_of_menu">Adresse</a></li>
		<li><a href="admin_srb_sendung_hf/index.php">Sendung HF</a></li>
		<li><a href="admin_srb_dispo/index.shtml">Dispo</a></li>
		<li><a href="admin_srb_verleih/index.php">Verleih</a></li>
		<li><a href="admin_srb_events/index.php">Events</a></li>
		<li><a href="admin_srb_weitere/index.shtml">Weitere</a></li>
	</ul>
</div>
