<div class="menu_list" id="jq_slide_by_click_1"> 
	<p class="menu_head"><a href="index.php">Admin-Home</a>	</p>
	<p class="menu_head">Play-Out - Actions</p>
	<div class="menu_body">
		<a href="../../admin_srb_play_out/controller_audio_switch.php">Audio-Switch Sendesignal</a>
		<a href="../../admin_srb_play_out/play_out_actions.php">Play-Out Actions durchführen</a>
	</div>		

	<p class="menu_head">Play-Out - Action-Log</p>
	<div class="menu_body">
		<a href="../../admin_srb_play_out/play_out_log_find_list.php?action=list_last_hour_all">Gesamt verg. Stunde</a>
		<a href="../../admin_srb_play_out/play_out_log_find_list.php?action=list_today_all">Gesamt heute</a>	
		<a href="../../admin_srb_play_out/play_out_log_find_list.php?action=list_yesterday_all">Gesamt gestern</a>				
		<a href="../../admin_srb_play_out/play_out_log_find_list.php?action=list_date_all">Gesamt nach Datum</a>
		<a href="../../admin_srb_play_out/play_out_log_find_list.php?action=list_today_play_out">Gespielte Titel heute/ Datum</a>
		<a href="../../admin_srb_play_out/play_out_log_find_list.php?action=list_date_notifications">Notifications heute/ Datum</a>
		<a href="../../admin_srb_play_out/play_out_log_find_list.php?action=list_date_informations">Informations heute/ Datum</a>
		<a href="http://stream.max-fm.com:8000/">Stream - Statistik aktuell</a>
		<a href="http://stream.max.fm/streamstats/srb/">Stream - Statistik Uebersicht</a>
	</div>		

	<p class="menu_head">Play-Out - Error-Log</p>
	<div class="menu_body">
		<a href="../../admin_srb_play_out/play_out_log_find_list.php?action=list_last_hour_error">Fehler verg. Stunde</a>
		<a href="../../admin_srb_play_out/play_out_log_find_list.php?action=list_today_error">Fehler heute</a>			
		<a href="../../admin_srb_play_out/play_out_log_find_list.php?action=list_yesterday_error">Fehler gestern</a>
		<a href="../../admin_srb_play_out/play_out_log_find_list.php?action=list_befor_yesterday_error">Fehler vorgestern</a>
		<a href="../../admin_srb_play_out/play_out_log_find_list.php?action=list_date_error">Fehler nach Datum</a>
	</div>				
	
	<p class="menu_head">Einstellungen</p>
	<div class="menu_body">
		<a href="../../admin_srb_user/user_special_find_list.php?action=list&amp;find_option=begin">Einstellung listen</a>
		<a href="../../admin_srb_user/user_special_edit.php?action=new&amp;special_id=0">Einstellung neu</a>
	</div>				
		
	<p class="menu_head">Formulare</p>
	<div class="menu_body">
		<a href="../../admin_srb_user/user_special_detail.php?action=display&amp;special_id=1048516">Nutzeranmeldung</a>
		<a href="../../admin_srb_user/user_special_detail.php?action=display&amp;special_id=1060379">Nutzer-Einwilligung</a>
		<a href="../../admin_srb_user/user_special_detail.php?action=display&amp;special_id=1049941">Sendeanmeldung</a>
		<a href="../../admin_srb_user/user_special_detail.php?action=display&amp;special_id=1064863">Leihschein</a>
	</div>		
	
	<p class="menu_head">Admin - Intranet</p>
	<div class="menu_body">
		<a href="../../xampp/index.php" target="_blank">XAMPP Administration</a>
		<a href="../../phpmyadmin/" target="_blank">phpMyAdmin</a>
	</div>		
	
	<p class="menu_head">Admin - Audiotechnik</p>
	<div class="menu_body">
		<a href="http://192.168.5.5" target="_blank">MAYAH C1141 User-Interface</a>
	</div>		
	
	<p class="menu_head">Admin - Benutzer</p>
	<div class="menu_body">
		<a href="../../admin_srb_user/user_account_find_list.php?action=list&amp;find_option=benutzer_name">Benutzer listen</a>
		<a href="../../admin_srb_user/user_account_edit.php?action=new&amp;account_id=0" class='c_box'>Benutzer neu</a>
	</div>				
	
	<p class="menu_head">Inventar</p>
	<div class="menu_body">
		<a href="../../admin_srb_inventar/index.php">Inventar Home</a>
		<a href="../../admin_srb_inventar/iv_find.php">Inventar finden</a>
		<a href="../../admin_srb_inventar/iv_edit.php?action=new&amp;iv_id=1" class='c_box'>Inventar eintragen</a>
		<a href="../../admin_srb_inventar/iv_find_list.php?action=list&amp;find_option=gesamt">Inventar listen</a>
	</div>				
	<p class="menu_head">LookUps</p>
	<div class="menu_body">
		<a href="../../admin_srb_user/user_look_ups_list.php?action=list&amp;find_option=ad_titel">Adresse Titel</a>
		<a href="../../admin_srb_user/user_look_ups_edit.php?action=new&amp;id=0&amp;lu_item=ad_titel" class='c_box'>Adresse Titel neu</a>		
		<a href="../../admin_srb_user/user_look_ups_list.php?action=list&amp;find_option=iv_kategorie">Inventar Kategorien</a>	
		<a href="../../admin_srb_user/user_look_ups_edit.php?action=new&amp;id=0&amp;lu_item=iv_kategorie" class='c_box'>Inventar Kategorie neu</a>		
		<a href="../../admin_srb_user/user_look_ups_list.php?action=list&amp;find_option=iv_eigentuemer">Inventar Eigentuemer</a>
		<a href="../../admin_srb_user/user_look_ups_edit.php?action=new&amp;id=0&amp;lu_item=iv_eigentuemer" class='c_box'>Inventar Eigentuemer neu</a>
		<a href="../../admin_srb_user/user_look_ups_list.php?action=list&amp;find_option=sg_genre">Sendung Genre</a>
		<a href="../../admin_srb_user/user_look_ups_edit.php?action=new&amp;id=0&amp;lu_item=sg_genre" class='c_box'>Sendung Genre neu</a>
		<a href="../../admin_srb_user/user_look_ups_list.php?action=list&amp;find_option=sg_sprache">Sendung Sprache</a>
		<a href="../../admin_srb_user/user_look_ups_edit.php?action=new&amp;id=0&amp;lu_item=sg_sprache" class='c_box'>Sendung Sprache neu</a>
	</div>

	<p class="menu_head">Externes</p>
	<div class="menu_body">
		<a href="https://mydrive.ch" target="_blank">MyDrive - externer Datentransfer</a>
		<a href="http://www.srb.fm/mobile/" target="_blank">SRB-Mobile Beta</a>
	</div>				
	
	
</div>
