<div class="content">
<div>
	<a href="../../admin_srb_play_out/play_out_log_find_list.php?action=list_last_hour_all" title='Action-Log, gesamt vergangene Stunde'><img src='../parts/pict/gnome-panel-workspace-switcher.png' width='48px' height='48px' title='Action-Log, gesamt vergangene Stunde' alt='Action-Log, gesamt vergangene Stunde'></a>
	<a href="../../admin_srb_play_out/play_out_log_find_list.php?action=list_today_all" title='Action-Log, gesamt heute'><img src='../parts/pict/1344495986_terminal.png' width='48px' height='48px' title='Action-Log, gesamt heute' alt='Action-Log, gesamt heute'></a>	
	<a href="../../admin_srb_play_out/play_out_log_find_list.php?action=list_today_error" title='Error-Log, gesamt heute'><img src='../parts/pict/mail-mark-important.png' width='48px' height='48px' title='Error-Log, gesamt heute' alt='Error-Log, gesamt heute'></a>			
</div>
</div>

 